repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.8

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/adamchainz/django-upgrade
  rev: ""  # replace with latest tag on GitHub
  hooks:
  -   id: django-upgrade
      args: [--target-version, "4.1"]   # Replace with Django version

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
      - id: debug-statements # Check for debugger imports and breakpoint() in python files
      - id: check-ast # Simply check whether files parse as valid python
      - id: fix-byte-order-marker # removes UTF-8 byte order marker
      - id: check-json
      - id: detect-private-key # detect-private-key is not in repo
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
      - id: trailing-whitespace
      - id: mixed-line-ending
