# Generated by Django 4.1 on 2023-05-05 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interface", "__first__"),
        ("face", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraExtractionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(
                        choices=[
                            (1, "每1秒抽取1张图片"),
                            (2, "每2秒抽取1张图片"),
                            (3, "每2秒抽取1张图片"),
                        ],
                        verbose_name="抽帧频率",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
            ],
            options={
                "verbose_name": "摄像头抽帧设置",
                "verbose_name_plural": "摄像头抽帧设置",
            },
        ),
        migrations.CreateModel(
            name="FaceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity", models.FloatField(verbose_name="相似度阈值")),
                (
                    "quality",
                    models.IntegerField(
                        choices=[(0, "无"), (1, "低"), (2, "中"), (3, "高")],
                        verbose_name="质量要求",
                    ),
                ),
                (
                    "face_group",
                    models.ManyToManyField(
                        to="face.facegroup", verbose_name="关联人脸组"
                    ),
                ),
            ],
            options={
                "verbose_name": "人脸库设置",
                "verbose_name_plural": "人脸库设置",
            },
        ),
        migrations.CreateModel(
            name="CameraGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camera_group_id",
                    models.CharField(max_length=50, verbose_name="摄像头组ID"),
                ),
                ("name", models.CharField(max_length=30, verbose_name="分组名")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="分组描述",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "摄像头分组",
                "verbose_name_plural": "摄像头分组",
                "unique_together": {("user", "camera_group_id")},
            },
        ),
        migrations.CreateModel(
            name="AISkillSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coordinates",
                    models.CharField(max_length=255, verbose_name="图像划分区域坐标"),
                ),
                (
                    "ai_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interface.aiskill",
                        verbose_name="AI技能绑定",
                    ),
                ),
                (
                    "face_relevance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camera.facesettings",
                        verbose_name="人脸库关联(可选)",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI技能配置",
                "verbose_name_plural": "AI技能配置",
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camera_id",
                    models.CharField(max_length=50, verbose_name="摄像头ID"),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="摄像头名称"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="摄像头描述",
                    ),
                ),
                (
                    "camera_url",
                    models.CharField(max_length=255, verbose_name="视频流地址"),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (10, "连接失败"),
                            (11, "连接成功"),
                            (12, "抽帧已配置"),
                            (13, "配置完成"),
                            (20, "工作中出错"),
                            (21, "工作中"),
                            (22, "已暂停"),
                        ],
                        verbose_name="摄像头状态",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
                (
                    "ai_skill_settings",
                    models.ManyToManyField(
                        blank=True,
                        to="camera.aiskillsettings",
                        verbose_name="所用AI技能",
                    ),
                ),
                (
                    "extraction_settings",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camera.cameraextractionsettings",
                        verbose_name="抽帧设置",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camera.cameragroup",
                        verbose_name="所属分组",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "摄像头配置",
                "verbose_name_plural": "摄像头配置",
                "unique_together": {("user", "camera_id")},
            },
        ),
    ]
