# Generated by Django 3.0 on 2020-10-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facesettings',
            name='face_group',
            field=models.ManyToManyField(to='face.FaceGroup', verbose_name='关联人脸组'),
        ),
    ]
