# Generated by Django 3.0 on 2020-10-26 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0002_facesettings_face_group'),
        ('interface', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cameragroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='camera',
            name='ai_skill_settings',
            field=models.ManyToManyField(blank=True, to='camera.AISkillSettings', verbose_name='所用AI技能'),
        ),
        migrations.AddField(
            model_name='camera',
            name='extraction_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camera.CameraExtractionSettings', verbose_name='抽帧设置'),
        ),
        migrations.AddField(
            model_name='camera',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.CameraGroup', verbose_name='所属分组'),
        ),
        migrations.AddField(
            model_name='camera',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='aiskillsettings',
            name='ai_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.AISkill', verbose_name='AI技能绑定'),
        ),
        migrations.AddField(
            model_name='aiskillsettings',
            name='face_relevance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camera.FaceSettings', verbose_name='人脸库关联(可选)'),
        ),
        migrations.AlterUniqueTogether(
            name='cameragroup',
            unique_together={('user', 'camera_group_id')},
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('user', 'camera_id')},
        ),
    ]
