# Generated by Django 4.1 on 2023-05-05 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "face_group_id",
                    models.CharField(max_length=50, verbose_name="人脸组ID"),
                ),
                ("name", models.CharField(max_length=30, verbose_name="分组名")),
                (
                    "description",
                    models.CharField(
                        default="", max_length=300, verbose_name="分组描述"
                    ),
                ),
                (
                    "bound",
                    models.BooleanField(default=False, verbose_name="是否被使用"),
                ),
                (
                    "add_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "人脸库分组",
                "verbose_name_plural": "人脸库分组",
                "unique_together": {("user", "face_group_id")},
            },
        ),
        migrations.CreateModel(
            name="Face",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "face_id",
                    models.CharField(max_length=50, verbose_name="人脸ID"),
                ),
                ("name", models.CharField(max_length=30, verbose_name="姓名")),
                (
                    "face_image",
                    models.ImageField(
                        upload_to="faces/%Y/%m/%d", verbose_name="人脸照片"
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="face.facegroup",
                        verbose_name="所属分组",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "人脸上传",
                "verbose_name_plural": "人脸上传",
                "unique_together": {("user", "face_id")},
            },
        ),
    ]
