# Generated by Django 4.1 on 2023-05-05 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_skill_group_id",
                    models.CharField(max_length=50, verbose_name="AI技能组ID"),
                ),
                ("name", models.CharField(max_length=30, verbose_name="分组名")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        null=True,
                        verbose_name="分组描述",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI技能接口分组",
                "verbose_name_plural": "AI技能接口分组",
                "unique_together": {("user", "ai_skill_group_id")},
            },
        ),
        migrations.CreateModel(
            name="AISkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_skill_id",
                    models.CharField(max_length=50, verbose_name="AI技能ID"),
                ),
                ("name", models.CharField(max_length=30, verbose_name="接口名称")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        null=True,
                        verbose_name="接口描述",
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
                (
                    "ai_skill_url",
                    models.CharField(max_length=512, verbose_name="技能接口URL"),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "接口异常"), (1, "接口正常")], verbose_name="接口状态"
                    ),
                ),
                (
                    "bound",
                    models.BooleanField(default=False, verbose_name="是否被使用"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interface.aiskillgroup",
                        verbose_name="所属分组",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI技能接口配置",
                "verbose_name_plural": "AI技能接口配置",
                "unique_together": {("user", "ai_skill_id")},
            },
        ),
    ]
