# Generated by Django 3.0 on 2020-10-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_skill_id', models.CharField(max_length=50, verbose_name='AI技能ID')),
                ('name', models.CharField(max_length=30, verbose_name='接口名称')),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='接口描述')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('ai_skill_url', models.CharField(max_length=512, verbose_name='技能接口URL')),
                ('state', models.IntegerField(choices=[(0, '接口异常'), (1, '接口正常')], verbose_name='接口状态')),
                ('bound', models.BooleanField(default=False, verbose_name='是否被使用')),
            ],
            options={
                'verbose_name': 'AI技能接口配置',
                'verbose_name_plural': 'AI技能接口配置',
            },
        ),
        migrations.CreateModel(
            name='AISkillGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_skill_group_id', models.CharField(max_length=50, verbose_name='AI技能组ID')),
                ('name', models.CharField(max_length=30, verbose_name='分组名')),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='分组描述')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': 'AI技能接口分组',
                'verbose_name_plural': 'AI技能接口分组',
            },
        ),
    ]
