# Generated by Django 3.0 on 2020-10-26 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interface', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiskillgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.AISkillGroup', verbose_name='所属分组'),
        ),
        migrations.AddField(
            model_name='aiskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterUniqueTogether(
            name='aiskillgroup',
            unique_together={('user', 'ai_skill_group_id')},
        ),
        migrations.AlterUniqueTogether(
            name='aiskill',
            unique_together={('user', 'ai_skill_id')},
        ),
    ]
