# Generated by Django 4.1 on 2023-05-05 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interface", "__first__"),
        ("camera", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_id",
                    models.CharField(max_length=50, verbose_name="事件ID"),
                ),
                (
                    "incident_image",
                    models.ImageField(
                        upload_to="incident/%Y/%m/%d", verbose_name="捕捉到的图片"
                    ),
                ),
                ("response", models.TextField(verbose_name="请求响应")),
                (
                    "occurrence_time",
                    models.DateTimeField(verbose_name="事件发生时间"),
                ),
                (
                    "ai_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interface.aiskill",
                        verbose_name="所用AI接口",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="camera.camera",
                        verbose_name="所属设备",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "事件总览",
                "verbose_name_plural": "事件总览",
                "ordering": ["-occurrence_time"],
                "unique_together": {("user", "incident_id")},
            },
        ),
    ]
