# Generated by Django 3.0 on 2020-10-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=50, verbose_name='事件ID')),
                ('incident_image', models.ImageField(upload_to='incident/%Y/%m/%d', verbose_name='捕捉到的图片')),
                ('response', models.TextField(verbose_name='请求响应')),
                ('occurrence_time', models.DateTimeField(verbose_name='事件发生时间')),
            ],
            options={
                'verbose_name': '事件总览',
                'verbose_name_plural': '事件总览',
            },
        ),
    ]
