# Generated by Django 3.0 on 2020-10-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0002_facesettings_face_group'),
        ('interface', '0001_initial'),
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ai_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.AISkill', verbose_name='所用AI接口'),
        ),
        migrations.AddField(
            model_name='incident',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.Camera', verbose_name='所属设备'),
        ),
    ]
